### ISSUE TITLE
Question: Which servers are connected?

### ISSUE THREAD

**Issue by stefan-niedermann** [r10s/messenger-android#19]
I like your project very much, but i am concerned about all network activities.
I assume that the app ist **only** connecting to the imap server i configured, but i want to go sure when i saw that there is some "backend"-repository.
Does the app use (mandatory or optional) any third party server except the imap server i connect to?
Regards

**Comment by r10s** [comment]
Delta Chat really uses **only** your IMAP-server as given in setup. 

No single bytes goes to any other server. This is one of the basic features of Delta Chat. It does not watch your activities in any way.

**Comment by stefan-niedermann** [comment]
yey, great! thanks :))
