### ISSUE TITLE
Does it yet support TLS connection

### ISSUE THREAD

**Issue by donty** [r10s/messenger-android#24]
Not got the client working yet with our setup but I suspect it may be the form of connection. Is there a test for imap/smtp connection in the client to check config?

Love the idea btw :-)

**Comment by spanezz** [comment]
Same here: I set up the app on android, IMAP connections work but SMTP connections do not seem to be even attempted when sending data out. Having some debugging log in the app would be helpful to figure out what is going on. I don't see a setting to have STARTTLS on the smtp configuration, I don't know if that's significant, but it would be needed to connect to my server.

**Comment by spanezz** [comment]
I discovered that the current network blocks outgoing port 25, and enabled the server also on the submission port. On the server log, I get this, but no email submission, and no information client-side:
```
Feb  4 11:47:21 server postfix/smtpd[22751]: connect from unknown[2001:67c:1810:f051:c40f:25a1:efdc:5984]
Feb  4 11:47:22 server postfix/smtpd[22751]: lost connection after UNKNOWN from unknown[2001:67c:1810:f051:c40f:25a1:efdc:5984]
Feb  4 11:47:22 server postfix/smtpd[22751]: disconnect from unknown[2001:67c:1810:f051:c40f:25a1:efdc:5984]
```

**Comment by spanezz** [comment]
With adb logcat I have this:
```
02-04 12:37:28.004 27847 27864 I DeltaChat: T2: Connecting to SMTP-server "enricozini.org:587"...
02-04 12:37:28.014 27847 27864 E DeltaChat: T2: SSL-connect failed: Connection refused
02-04 12:37:28.014 27847 27864 E DeltaChat: 
```
But then from `adb shell` the connection succeeds:
```
$ nc enricozini.org 587
220 enricozini.org ESMTP Postfix (Debian/GNU)
HELO me
250 enricozini.org
QUIT
221 2.0.0 Bye
```

**Comment by tbart** [comment]
I have another variation of the problem.
My server needs STARTTLS as well.
Logcat however tells me:


```
02-07 08:40:33.001  2561  2578 I DeltaChat: T2: Job thread checks for pending jobs...
02-07 08:40:33.006  2561  2578 I DeltaChat: T2: Executing job #20, action 800...
02-07 08:40:33.007  2561  2578 I DeltaChat: T2: Connecting to SMTP-server "mail.myserver.com:587"...
02-07 08:40:33.208  2561  2578 E DeltaChat: T2: SSL-connect failed: Unknown error code
02-07 08:40:33.208  2561  2578 E DeltaChat: 
02-07 08:40:33.257  2561  2578 I DeltaChat: T2: Job #20 delayed for 600 seconds
02-07 08:40:33.261  2561  2578 I DeltaChat: T2: Job thread waiting for 207 seconds or signal...
```
K-9 Mail connects successfully. My phone runs CM.

The technology behind Delta Chat is a great idea! In fact, I told everyone "Why can't we just use email with a better frontend?" for years. Now someone came up and did it. Thanks a lot!

**Comment by daniel-k** [comment]
Same problem as @tbart here, just that I'm using port 25. If you need any input for debugging, just ask 🙂

**Comment by Neudrino** [comment]
Same problem here. My provider needs port 587 for SMTP. Setting port manually does not help.
F-Droid Version 0.1.21 on CM 13.0.

**Comment by r10s** [comment]
Thank you for your report, I'm adding support for this (and other configurations) just in this minute :-)
The next F-Droid version should support it then (in fact, it is already supported, but there is no real option for it yet...)
I'm also about to implement [autoconfigure](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration), so, with chance, it will work "automagically" then ;-)

**Comment by r10s** [comment]
STARTTLS should work with the upcoming 0.1.22
