### ISSUE TITLE
Delta crashes with mail-account by strato

### ISSUE THREAD

**Issue by rickcrash** [r10s/messenger-android#26]
Trying to use delta with my account by strato.de delta crashes immediately.
GMX.de and autistici.org are working fine.

**Comment by bokf** [comment]
I have Delta installed on two different phones (both Moto G3, CM12) using Strato on both. On one phone it works without crashing, on the second phone is crashes very often. After some tries it starts again. Sometimes it needs up to 10 tries to open again.

**Comment by rickcrash** [comment]
I tried it with my phone as well as with my tablet. Using strato leads to crashes on both devices, restart delta (even often) does not help.

**Comment by kr428** [comment]
Similar behaviour here but not on strato - tried using both company IMAP server and GMail accounts. Both lead to application force-close / crash on tablet (Android 4.4.4) as well as on phone (Android 7.1).

**Comment by aHVzY2g** [comment]
+1 @Strato

**Comment by aHVzY2g** [comment]
![screenshot_20170206-222636_52548c204332f70b93e0d2737f0ce3c2e3afc2d0](https://cloud.githubusercontent.com/assets/25596663/22711633/2b77ede4-ed82-11e6-961a-ca7bf1b737a6.png)
Here is some debbuging from CatLog.

**Comment by bokf** [comment]
Logging into the Webinterface the folders look like this:
![20170208104320](https://cloud.githubusercontent.com/assets/25562831/22731941/c2c8f408-edec-11e6-9dbf-ea1987c793a5.png)

**Comment by bokf** [comment]
At GMX I can see the new folder Chats, at Strato not:
![20170208105545](https://cloud.githubusercontent.com/assets/25562831/22732109/41c8560e-eded-11e6-95e5-cdf0eb2c5b12.png)

**Comment by aHVzY2g** [comment]
@bokf could you check if your "Archive" folder is empty? I guess that is what the roblem could be.

**Comment by r10s** [comment]
Hello together, thank you very much.

As I do not have a strato account and I think most strato packages come with lots of free e-mail accounts:

Can anyone give me a testing address? Please mail the needed information (mail, server, login etc.) to r10s AT b44t DOT com. Alternatively, you can use the phone number given at https://getdelta.org/en/imprint - but be warned: my english is baaaaad.

**Comment by rickcrash** [comment]
done.

**Comment by r10s** [comment]
The crash should be fixed by https://github.com/r10s/messenger-backend/commit/4617c76852087116913952d9e3d71cd4e132994f

**Comment by r10s** [comment]
If the crash is still present in the upcoming release (v0.1.19 or larger), please re-open this issue. For now, it is closed.
