### ISSUE TITLE
Unable to create initial account

### ISSUE THREAD

**Issue by petmos** [r10s/messenger-android#29]
I tried to test delta chat on my old tablet with Android 4.2.2. When I started delta chat it asked my to insert my email address.
But I my input wasn't shown in the input field.
So I tapped long on this field until the cursor came up. But after releasing my finger from the input field the cursor disappeared immediatly.
So I can't create a first account.
But entering a password is possible.

**Comment by petmos** [comment]
Okay, I tried some different keyboard settings and now I'm able to create an account but:
I use a gmail address and Google aked me: "Zugriff weniger sicherer Apps auf Ihr Konto zulassen.
Google blockiert möglicherweise Anmeldeversuche von Apps und Geräten, die nicht den modernen Sicherheitsstandards entsprechen. Da sich andere Personen einfacher Zugriff auf diese Apps und Geräte verschaffen können, blockieren wir sie, um Ihr Konto zu schützen."
because your access methode isn't safe enough.

**Comment by r10s** [comment]
Thank you for your report; we already know about this issue, see issue #20
