### ISSUE TITLE
File Attaches

### ISSUE THREAD

**Issue by stefankeppler** [r10s/messenger-android#30]
First off: Great Project!
If encryption and all ohter features will work, it will be the best messanger ever!

If I attach file in deltachat and send it, it will be usable on linux with Thunderbird.
If I attach a mp3 in Thunderbid and send it to Deltachat, I will see an attach and a slider without play-button. I can't find a way to use the mp3 on the phone.

**Comment by r10s** [comment]
First, thank you for the kudos.

Regarding attachments: We know this is not really working yet, see issue #13
