### ISSUE TITLE
Handle contacts with multiple mail addresses

### ISSUE THREAD

**Issue by escoand** [r10s/messenger-android#34]
Most of my contacts have multiple mail addresses but they are just recognized by Delta Chat if I/they send with/to the exact address the chat was started with

An other issue is Delta Chat always responses with the configured address, but I have multiple address. One for private one for business. I could ask which one to use for response.

**Comment by r10s** [comment]
We already though about this issue, but we came to the conclusion that `chat:email` should be `1:1` for the following reasons:

- 1:n are often old email addresses or work/private/whatever addresses:
- for old addresses: No problem, the old addresses will go down in the list sooner or later
- for work/private/whatever addresses: Often it is a good idea to keep them separated  - using 1:1, you can easily decide where to reach a person
- people using multiple e-mail-addresses may use forwarding - or may not. So it would  be unclear, if outgoing mails go to one address or to all
- Using such a contact in groups would be even more complicated
- KISS ;-)

**Comment by escoand** [comment]
OK, I understand this but:
A friend started a chat with me, I responded but had configured an other address.
So he could not see my response in the chat but has to use a mail client just to recognize the new messages.
What is your propose for this problem?

**Comment by r10s** [comment]
If your friend contacts you and you answer using Delta Chat, the answer will always go to the same email address. You can't configure another address.

I do not see a problem in this example.

But it may  be an good example why not to use `1:n`: In  this case it may happen, you answer to an address that is read by the sender in the situation: Imagine you have a chat with the email-addresses work@foo.bar and private@foo.bar: You may have configured the chat to send to private@foo.bar - if then there comes a mail from work@foo.bar, your answer will not be recognized by the sender.

There may be situations, where 1:n is useful, of course. But I think there are at least the same number of situations, where 1:1 is more useful and 1:n  is confusing. Regarding this, I see no reason to add extra complexibility to the user interface, to the structure and to the code.

However, I'll keep the issue open for discussion.

**Comment by escoand** [comment]
I would say the reason for my issue is #53. This can be closed...
