### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by aggsol** [r10s/messenger-android#35]
* It is very hard to find the repository and information about the app if you only know the name "Delta Chat". Even with the search box on GitHub itself it is hard to find (also try a search engine of your liking). Some renaming of the repos would help.

* The relation of back end and front end  is difficult to understand. How about a diagram? Allwoing the Wiki and the repos would also help?

* When I setup the app I can receive email but not send, there is no error message or log. It is very frustrating to debug when something is not working

* Keep up the good work, it's a great idea. :+1:

**Comment by stefan-niedermann** [comment]
> The relation of back end and front end is difficulat to understand. 

Jup, i asked the same question (https://github.com/r10s/messenger-android/issues/19). Maybe it would be better to rename the `backend` repository to `lib` or `core` or so.

**Comment by r10s** [comment]
> It is very hard to find the repository and information about the app if you only know the name "Delta Chat". Even with the search box on GitHub itself it is hard to find (also try a search engine of your liking). Some renaming of the repos would help.

Well, for the moment, this is okay. The app is not yet ready-to-use for everyone, we have to fix lots of bugs first.

> The relation of back end and front end is difficult to understand. How about a diagram? Allwoing the Wiki and the repos would also help?

Frontend (eg. Android): Render the GUI 
Backend: Communicate with IMAP, SMTP, handle the database etc.
Both, Frontend and Backend, run locally.

If we have a diagram, I would be glad to link it here ;-)

However, maybe `messenger-lib` or `messenger-core` would be better choices, don't know.

**Comment by r10s** [comment]
> When I setup the app I can receive email but not send, there is no error message or log. It is very frustrating to debug when something is not working

Unsend messages are reported to the user by missing checkmarks. An alert is unwanted here, as it is quite usual, the network is not reachable at a given moment; Delta Chat automatically tries over later then.

Failed sending is logged to the normal Android protocol using the [Log class](https://developer.android.com/reference/android/util/Log.html). 

However, setting up the account itself is improvable, see https://github.com/r10s/messenger-backend/issues/5

**Comment by r10s** [comment]
Finally, we've renamed the repositories to deltachat-android and deltachat-core - thank you for your help!
