### ISSUE TITLE
sending mail address outside contact list

### ISSUE THREAD

**Issue by bobblkabb** [r10s/messenger-android#40]
Is there a way to directly insert a mail recipient which is not maintained inside the address book?

**Comment by r10s** [comment]
> Is there a way to directly insert a mail recipient which is not maintained inside the address book?

Yes, use "New chat / New user".  "New user" is also available in other situations, eg. when creating a new group.

![screenshot_20170208-161311](https://cloud.githubusercontent.com/assets/9800740/22743243/efcd193e-ee19-11e6-976a-5cfc8b89f5de.png)
