### ISSUE TITLE
Send email to myself

### ISSUE THREAD

**Issue by EMK2000** [r10s/messenger-android#41]
I have tried to talk to myself in the app, and then my inbox actually received an email from myself. 

But when I tried reply to myself in the inbox, the inbox showed the reply message, but there wasn't any new message in the app. 

Isn't it weird?

**Comment by EMK2000** [comment]
If I send an email using the app, but my friend hasn't installed the app, and he reply to me using the inbox, in general will I received a reply message in the app, the same chat?

**Comment by r10s** [comment]
> I have tried to talk to myself in the app, and then my inbox actually received an email from myself.
> But when I tried reply to myself in the inbox, the inbox showed the reply message, but there wasn't any new message in the app.
> Isn't it weird?

No, currently, this is "by design", the messages just appears later. We've added a detailed description at https://github.com/r10s/messenger-backend/issues/12

> If I send an email using the app, but my friend hasn't installed the app, and he reply to me using the inbox, in general will I received a reply message in the app, the same chat?

Yes.
