### ISSUE TITLE
Autodiscover of IMAP / SMTP settings

### ISSUE THREAD

**Issue by jbacksch** [r10s/messenger-android#45]
Autodiscover of IMAP / SMTP settings like:

- Thunderbird <https://wiki.mozilla.org/Thunderbird:Autoconfiguration:UI>
- Outlook <https://technet.microsoft.com/library/bb124251%28v=exchg.150%29.aspx>

**Comment by r10s** [comment]
also see https://github.com/r10s/messenger-backend/issues/5
