### ISSUE TITLE
yandex: Sending ok / Not seeing chats

### ISSUE THREAD

**Issue by thesnable** [r10s/messenger-android#52]
Sending works. Messages are in the box. But i do t see them in the inbox of delta chat. or with my chat contacts.

**Comment by r10s** [comment]
thank you for your report. do you mean this mail service: https://mail.yandex.com/ ?

**Comment by thesnable** [comment]
yes
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.02.17, 12:29, "Björn Petersen" <notifications@github.com> schrieb:

  
    
      thank you for your report. do you mean this mail service: https://mail.yandex.com/ ?

**Comment by r10s** [comment]
I've just tested it with the upcoming 0.1.22 (with many new send/receive features), receiving and sending works as expected.
