### ISSUE TITLE
Delta does not recognize new messages

### ISSUE THREAD

**Issue by escoand** [r10s/messenger-android#53]
Delta does not recognize new messages on qmail server. Also the in-box is empty. So it is not possible to chat.

**Comment by rickcrash** [comment]
Same thing here, using an strato-account with delta. By now that error occurs only with specific senders, so the problem seems to be caused by the sender.

**Comment by r10s** [comment]
> By now that error occurs only with specific senders, so the problem seems to be caused by the sender.

Are you sure, the missing messages are not in the "Inbox"? (Delta Chat only shows messages of explicitly chosen contacts or of contacts actively contacted by you).

Otherwise, can you find out, which messages do not pop up  in Delta Chat? If you can send us an eml-file of these messages or other appropriate information, we can check this issue.

**Comment by escoand** [comment]
```
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on
	domain1.com
X-Spam-Level: 
X-Spam-Status: No, score=-1.9 required=7.0 tests=BAYES_00,T_DKIM_INVALID,
	URIBL_BLOCKED autolearn=ham version=3.3.1
Received: (qmail 2660 invoked from network); 26 Feb 2017 19:20:00 +0100
Received: from domain6.com (HELO domain2.com) (5.6.7.8)
  by domain5.com with (DHE-RSA-AES256-SHA encrypted) SMTP; 26 Feb 2017 19:20:00 +0100
Received: from localhost (p57AF67BE.dip0.t-ipconnect.de [1.2.3.4])
	by domain2.com (Postfix) with ESMTPSA id B622C12460FDD
	for <user1@domain3.com>; Sun, 26 Feb 2017 19:19:59 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=domain4.com;
	s=default; t=1488133200;
	bh=Enr7X+8+OMWu+xdlTZOuuMNkCMuMxTy8Etj5vzxkE4c=; l=67;
	h=From:To:Subject;
	b=WPch25zeYLAdxQEra/N+x2+mJnSu7nJyznl+7PKLvo5Rt8rr8J5ZvqUIhCtWfBiU8
	 5R2LHn5A7xj2oSJuC6rqEndIYx9LLTrxXpJeEr0aZ+LyF2vzqJq8aUA2N3mq5WPCdv
	 7i3mThQJb5wxosOCQUqEVubFMszBHEK4jQ4XdjSk=
Date: Sun, 26 Feb 2017 19:20:01 +0100
From: user2@domain4.com
To: Test <user1@domain3.com>
Message-ID: <Mr.WLMcUS-3WpJ.user2@domain4.com>
Subject: =?utf-8?Q?Chat=3A?= Ein neuer Versuch
X-Mailer: MrMsg 0.1.19
X-MrMsg: 1.0
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
X-PPP-Message-ID: <20170226181959.11124.81363@domain2.com>
X-PPP-Vhost: domain4.com

Ein neuer Versuch

-- 
Mit meinem Delta Chat Messenger gesendet
```

**Comment by escoand** [comment]
Was this mail helpful?

**Comment by r10s** [comment]
I've tested strato successfull, Delta Chat 0.1.22 comes with a _lot_ connectivity improvements, so with chance, this is working now.

For testing, first try to click the checkmark in the upper right corner of the "account settings" ...
 
![image](https://cloud.githubusercontent.com/assets/9800740/24245481/4c20a2e4-0fc3-11e7-9eb5-a6f9fef2b3b1.jpg)
... or deinstall Delta Chat and install the upcoming 0.1.22 again from F-Droid. Thank you very much for your help.

**Comment by escoand** [comment]
I was now able to test the issue again on my old phone, and for me it still exists. Are you interested in my test account? PM?a

**Comment by r10s** [comment]
A test account would be helpfull , just mail to to r10s@b44t.com
