### ISSUE TITLE
Received emojis / smilies appear as special character in mailclient

### ISSUE THREAD

**Issue by lombard0** [r10s/messenger-android#57]
I dont' know if hat issue concerns delta, but receiving messages in tradtional email client like thunderbird (but also on webmail interface) with smilies from selection leads to special character: �

I'm using v0.1.21 and Blackberry OS 10.3.2.2836

**Comment by lombard0** [comment]
I dont' know if hat issue concerns delta, but receiving messages in tradtional email client like thunderbird (but also on webmail interface) with smilies from selection leads to special character: �

I'm using v0.1.21 and Blackberry OS 10.3.2.2836

**Comment by r10s** [comment]
No, this is no issue with Delta Chat. It's up to the receiver's client to show up the emojis / smilies properly. Technically, they're just unicode characters, not much different than letters.

**Comment by luisfsr** [comment]
I installed symbola fonts on my computer (ubuntu) and the emojis showed properly when I visualize DC messages from my computer. But what about people who don't have this minimal technical knowledge?
Perhaps DC could automatically change the emojis from unicode characters to an image file before delivering the e-mail, so the receiver would visualize it as an emoji... Would it be possible?
