### ISSUE TITLE
Can't set chat background

### ISSUE THREAD

**Issue by StefRe** [r10s/messenger-android#64]
Settings | Chat background lets you select an image from the gallerie or take a picture with the camera, but then this image isn't set as background (nothing happens).

**Comment by r10s** [comment]
Normally, the wallpaper backgounds work like a charm.

- have you clicked the checkbox in the upper-right corner of the wallpaper selection dialog?
- the background is only visible in a "opened chat", not in the "chat overview"

**Comment by StefRe** [comment]
Strange. It works like a charm as soon as I have sent the first message. On a fresh install, however, nothing happens (i.e. install Delta chat, go to setting, chat background). The background of the settings dialog doesn't change, so there's no point in clicking the checkbox in the upper right corner.
Tested with version 0.1.23.

**Comment by r10s** [comment]
Okay, that's a good hint, I'll test it again with a fresh install.

Thank you very much.

**Comment by kskarthik** [comment]
Works without any problem on v0.1.28

**Comment by r10s** [comment]
I also did not found out any further problems, so, for now, I close this issue.
