### ISSUE TITLE
how long is the keep alive/heartbeat interval?

### ISSUE THREAD

**Issue by zoff99** [r10s/messenger-android#72]
how many seconds is it now? where in the code is it?
can it be configured to high values?

**Comment by r10s** [comment]
There is no single "heartbeat" interval. Things are much more complicated these days as Google wants everyone to use their GCM/FCM ...

However, Delta Chat does the following to keep the connection alive and to get instant notifications:
- send IDLE command to server
- in a second thread, make sure the IDLE thread is working as desired. If not, we're reconnecting. We check this normally about every minute ...
- as this second thread may be delayed by the OS, we use an additional Timer that should also work in DOZE mode, this timer is also called about every minute  
(the "minute" mentioned here is just to check if something fails. This is not the time, Delta Chat checks for new messages. The messages appear normally much faster in a second or so, this depends on your server)

- we do not use *REQUEST_IGNORE_BATTERY_OPTIMIZATION as Google may reject such apps from their store, see https://developer.android.com/training/monitoring-device-state/doze-standby.html#support_for_other_use_cases : "Google Play policies prohibit apps from requesting direct exemption from Power Management features in Android 6.0+ (Doze and App Standby) unless the core function of the app is adversely affected." Instead, we're using a foreground service, which seems to work well.
